<?php

declare(strict_types=1);

use Phinx\Seed\AbstractSeed;

final class RestaurantsSeeder extends AbstractSeed
{
    public function run(): void
    {
        $rows = [
            [
                'name' => 'Café de Roemer',
                'slug' => 'cafe-de-roemer',
                'address' => 'Botermarkt 17, 2011 XL Haarlem',
                'type' => 'Dutch, fish and seafood, European',
                'image' => 'Cafe-de-Roemer.jpg',
                'sessions' => 3,
                'duration_hours' => 1.5,
                'first_session' => '18:00:00',
                'second_session' => '19:30:00',
                'third_session' => '21:00:00',
                'stars' => 4,
                'seats' => 35,
                'price_adult' => 35.00,
                'price_kid' => 17.50,
                'kid_age_max' => 12,
                'walk_minutes_to_patronaat' => 8,
            ],
            [
                'name' => 'Ratatouille',
                'slug' => 'ratatouille',
                'address' => 'Spaarne 96, 2011 CL Haarlem, Nederland',
                'type' => 'French, fish and seafood, European',
                'image' => 'Ratatouille.jpg',
                'sessions' => 3,
                'duration_hours' => 2.0,
                'first_session' => '17:00:00',
                'second_session' => '19:00:00',
                'third_session' => '21:00:00',
                'stars' => 4,
                'seats' => 52,
                'price_adult' => 45.00,
                'price_kid' => 22.50,
                'kid_age_max' => 12,
                'walk_minutes_to_patronaat' => 14,
            ],
            [
                'name' => 'Restaurant ML',
                'slug' => 'restaurant-ml',
                'address' => 'Kleine Houtstraat 70, 2011 DR Haarlem, Nederland',
                'type' => 'Dutch, fish and seafood, European',
                'image' => 'Restaurant-ML.jpg',
                'sessions' => 2,
                'duration_hours' => 2.0,
                'first_session' => '17:00:00',
                'second_session' => '19:00:00',
                'third_session' => '21:00:00',
                'stars' => 4,
                'seats' => 60,
                'price_adult' => 45.00,
                'price_kid' => 22.50,
                'kid_age_max' => 12,
                'walk_minutes_to_patronaat' => 11,
            ],
            [
                'name' => 'Restaurant Fris',
                'slug' => 'restaurant-fris',
                'address' => 'Twijnderslaan 7, 2012 BG Haarlem, Nederland',
                'type' => 'Dutch, French, European',
                'image' => 'Restaurant-Fris.jpg',
                'sessions' => 3,
                'duration_hours' => 1.5,
                'first_session' => '17:30:00',
                'second_session' => '18:00:00',
                'third_session' => '19:30:00',
                'stars' => 4,
                'seats' => 45,
                'price_adult' => 45.00,
                'price_kid' => 22.50,
                'kid_age_max' => 12,
                'walk_minutes_to_patronaat' => 22,
            ],
            [
                'name' => 'New Vegas',
                'slug' => 'new-vegas',
                'address' => 'Koningstraat 5, 2011 TB Haarlem',
                'type' => 'Veganistisch',
                'image' => 'New-Vegas.jpg',
                'sessions' => 3,
                'duration_hours' => 1.5,
                'first_session' => '17:00:00',
                'second_session' => '18:30:00',
                'third_session' => '20:00:00',
                'stars' => 3,
                'seats' => 36,
                'price_adult' => 35.00,
                'price_kid' => 17.50,
                'kid_age_max' => 12,
                'walk_minutes_to_patronaat' => 8,
            ],
            [
                'name' => 'Grand Cafe Brinkman',
                'slug' => 'grand-cafe-brinkman',
                'address' => 'Grote Markt 13, 2011 RC Haarlem, Nederland',
                'type' => 'Dutch, European, Modern',
                'image' => 'Grand-Cafe-Brinkman.jpg',
                'sessions' => 3,
                'duration_hours' => 1.5,
                'first_session' => '16:30:00',
                'second_session' => '18:00:00',
                'third_session' => '19:30:00',
                'stars' => 3,
                'seats' => 100,
                'price_adult' => 35.00,
                'price_kid' => 17.50,
                'kid_age_max' => 12,
                'walk_minutes_to_patronaat' => 9,
            ],
            [
                'name' => 'Urban Frenchy Bistro Toujours',
                'slug' => 'toujours',
                'address' => 'Oude Groenmarkt 10-12, 2011 HL Haarlem, Nederland',
                'type' => 'Dutch, fish and seafood, European',
                'image' => 'Toujours.jpg',
                'sessions' => 3,
                'duration_hours' => 1.5,
                'first_session' => '17:30:00',
                'second_session' => '19:00:00',
                'third_session' => '20:30:00',
                'stars' => 3,
                'seats' => 48,
                'price_adult' => 35.00,
                'price_kid' => 17.50,
                'kid_age_max' => 12,
                'walk_minutes_to_patronaat' => 11,
            ],
        ];

        $this->table('restaurants')->truncate();
        $this->table('restaurants')->insert($rows)->saveData();
    }
}